COLORTERM=truecolor
SSH_AUTH_SOCK=%t/openssh_agent
GPG_AGENT_INFO=%t/gnupg/S.gpg-agent
PATH=/home/manuel/.cargo/bin:/home/manuel/.asdf/shims:/home/manuel/.local/share/miniconda3/bin:/usr/local/go/bin:/home/manuel/workbench/go/bin:/home/manuel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
